### Login via JSON API
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "email": "student@example.com",
  "password": "student123"
}

### Si retorna la pantalla de dashboard está trabajando bien
### Si retorna la pantalla de login significa que existe
### algún problema con las credenciales del usuario utilizado.