### Editar una receta (POST)

# Simular POST con nuevos datos del la receta
# En este caso, se actualiza la receta con ID 4
# Se asume que la receta con ID 4 ya existe en la base de datos
# y se desea actualizar su información.

PUT http://localhost:5000/recetas/7
Content-Type: application/json

{
  "nombre": "Tarta de Queso Actualizada",
  "ingredientes": "Queso crema, azúcar morena, huevos, base de galleta",
  "instrucciones": "Mezclar todo, verter en un molde y hornear por 50 minutos.",
  "tiempo_preparacion": 55,
  "porciones": 10,
  "imagen_url": "http://example.com/cheesecake_updated.jpg",
  "categoria": "Postres",
  "usuario_id": 1
}
